### ISSUE TITLE
Possible UCP

### ISSUE THREAD

**Issue by sabrelsrp** [aholyshit/lsrp-samp-gamemode#11]
Will the UCP ever been released?

**Comment by Viethuang** [comment]
Hopeee

**Comment by Viethuang** [comment]
u have discord?

**Comment by aholyshit** [comment]
> u have discord?

MoonMan#1606

**Comment by Viethuang** [comment]
> MoonMan#1606

acp

**Comment by aholyshit** [comment]
[i](https://github.com/aholyshit/lsrp-ucp)

**Comment by aholyshit** [comment]
https://github.com/aholyshit/lsrp-ucp
