### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by danilokatanic** [aholyshit/lsrp-samp-gamemode#5]
Hello. I gladly appreciate the person whoever published this version of LSRP gamemode,
however, a few things are missing to accordingly start the server. We would be blessed with the complete pawn script and the UCP website. I've faced several issues due to weird pawn script, can you update the pawn/include folder too? If you accept our request, please update us with the UCP.

**Comment by aholyshit** [comment]
Hello!
I added the community compiler and missing includes. Gamemode should get compiled without problems now.
The UCP might come too, or not. We'll see.

**Comment by ImperialDevs** [comment]
Yeah, disabling registration via the UCP still tells us that we need to create an account on the UCP rather than having us register in-game. Would really appreciate it if a fix is implemented for that or the UCP is provided.

Thanks!

**Comment by aholyshit** [comment]
There is /createaccount /createcharacter. All you have to do is manually create one master account and then add a character to it through phpmyadmin.

**Comment by ImperialDevs** [comment]
> There is /createaccount /createcharacter. All you have to do is manually create one master account and then add a character to it through phpmyadmin.

Yes but this is not helpful for servers that are wishing to use this script on a bigger scale. We need the UCP to run the server officially.
