### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by sabrelsrp** [aholyshit/lsrp-samp-gamemode#6]
I cant change the sql details in config.pwn

They just dont update, any help?

**Comment by meduza0199** [comment]
nevermind managed to fix it, now trying to setup accounts without a UCP, this is going to be fun

**Comment by meduza0199** [comment]
and doesnt allow manual setup as it doesnt read account password

**Comment by danilokatanic** [comment]
> and doesnt allow manual setup as it doesnt read account password

Because passwords are hashed. But you can make a hash password by yourself.

**Comment by meduza0199** [comment]
> > and doesnt allow manual setup as it doesnt read account password
> 
> Because passwords are hashed. But you can make a hash password by yourself.

Still doesnt work, even after hashing with SHA256 which SAMP uses

**Comment by meduza0199** [comment]
https://www.scopulus.co.uk/tools/passwordmastersha2.htm

Used this for example to hash the password but doesnt want to work

**Comment by aholyshit** [comment]
Whirlpool, not SHA256.

**Comment by meduza0199** [comment]
> Use Whirlpool, not SHA256.

is it the same for secret word?

**Comment by meduza0199** [comment]
Nevermind I managed to get ingame! Thank you, having the UCP would be nice eventually!
